CREATE TABLE IF NOT EXISTS `wallet`
(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用戶id',
    `amount` DECIMAL(19,4) NOT NULL COMMENT '錢包金額',
    `currency` VARCHAR(36) NOT NULL COMMENT '幣別',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    `deleted_at` TIMESTAMP NULL COMMENT '刪除時間',

    PRIMARY KEY (`id`),
    UNIQUE INDEX (`user_id`,`currency`)
) AUTO_INCREMENT=1 CHARSET=`utf8mb4` ENGINE=InnoDB COLLATE=`utf8mb4_general_ci` COMMENT '錢包';